version: "3"

services:
  postgres-server:
    container_name: 'chemtemp-dbserver'
    image: 'postgres:15.1'
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1postgres1
      - POSTGRES_DB=chem
    volumes:
      - /home/mark/datapg:/var/lib/postgresql/data

  pgadmin:
    container_name: 'pgadmin4'
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@strose.edu
      - PGADMIN_DEFAULT_PASSWORD=1admin1
    ports:
      - "50001:80"

